# Experiment 8
### Name- Shreya
### PRN- 25070123159
### Batch- A3
### Title- Tools for EDA: Study of Numpy Library

In [100]:
# Declaration of Numpy
import numpy as np
a = np.array([10,20,30,40])
b = np.array([[1,2,3],[4,5,6]])
print (a)
print (b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [73]:
# Dimension of Array
print(a.ndim)
print(b.ndim)

1
2


In [74]:
print(a.shape) #rows,columns
print(b.shape)

(4,)
(2, 3)


In [75]:
print (a.dtype)
print (b.dtype)

int64
int64


In [76]:
# In-Built functions using numpy
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [78]:
np.eye((3)) #Diagonal matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [80]:
np.linspace(0,1,4) # 1 is not exclusive

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [81]:
print (b * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [82]:
print (a + 5)

[15 25 35 45]


In [88]:
print (np.mean (a))
print (np.mean (b))

25.0
3.5


In [92]:
print (np.median (a))
print (np.median (b))

25.0
3.5


In [93]:
print (np.max(a))
print (np.min(a))

40
10


In [94]:
print (np.max(b))
print (np.min(b))

6
1


In [107]:
np.sum(a)

np.int64(100)

In [106]:
np.sum(b)

np.int64(21)